	unsaved u0 (
		.clk_clk                                                  (<connected-to-clk_clk>),                                                  //                                 clk.clk
		.reset_reset_n                                            (<connected-to-reset_reset_n>),                                            //                               reset.reset_n
		.memory_mem_a                                             (<connected-to-memory_mem_a>),                                             //                              memory.mem_a
		.memory_mem_ba                                            (<connected-to-memory_mem_ba>),                                            //                                    .mem_ba
		.memory_mem_ck                                            (<connected-to-memory_mem_ck>),                                            //                                    .mem_ck
		.memory_mem_ck_n                                          (<connected-to-memory_mem_ck_n>),                                          //                                    .mem_ck_n
		.memory_mem_cke                                           (<connected-to-memory_mem_cke>),                                           //                                    .mem_cke
		.memory_mem_cs_n                                          (<connected-to-memory_mem_cs_n>),                                          //                                    .mem_cs_n
		.memory_mem_dm                                            (<connected-to-memory_mem_dm>),                                            //                                    .mem_dm
		.memory_mem_ras_n                                         (<connected-to-memory_mem_ras_n>),                                         //                                    .mem_ras_n
		.memory_mem_cas_n                                         (<connected-to-memory_mem_cas_n>),                                         //                                    .mem_cas_n
		.memory_mem_we_n                                          (<connected-to-memory_mem_we_n>),                                          //                                    .mem_we_n
		.memory_mem_reset_n                                       (<connected-to-memory_mem_reset_n>),                                       //                                    .mem_reset_n
		.memory_mem_dq                                            (<connected-to-memory_mem_dq>),                                            //                                    .mem_dq
		.memory_mem_dqs                                           (<connected-to-memory_mem_dqs>),                                           //                                    .mem_dqs
		.memory_mem_dqs_n                                         (<connected-to-memory_mem_dqs_n>),                                         //                                    .mem_dqs_n
		.memory_mem_odt                                           (<connected-to-memory_mem_odt>),                                           //                                    .mem_odt
		.oct_rzqin                                                (<connected-to-oct_rzqin>),                                                //                                 oct.rzqin
		.mem_if_ddr3_emif_0_pll_ref_clk_clk                       (<connected-to-mem_if_ddr3_emif_0_pll_ref_clk_clk>),                       //      mem_if_ddr3_emif_0_pll_ref_clk.clk
		.mem_if_ddr3_emif_0_global_reset_reset_n                  (<connected-to-mem_if_ddr3_emif_0_global_reset_reset_n>),                  //     mem_if_ddr3_emif_0_global_reset.reset_n
		.mem_if_ddr3_emif_0_soft_reset_reset_n                    (<connected-to-mem_if_ddr3_emif_0_soft_reset_reset_n>),                    //       mem_if_ddr3_emif_0_soft_reset.reset_n
		.mem_if_ddr3_emif_0_pll_sharing_pll_mem_clk               (<connected-to-mem_if_ddr3_emif_0_pll_sharing_pll_mem_clk>),               //      mem_if_ddr3_emif_0_pll_sharing.pll_mem_clk
		.mem_if_ddr3_emif_0_pll_sharing_pll_write_clk             (<connected-to-mem_if_ddr3_emif_0_pll_sharing_pll_write_clk>),             //                                    .pll_write_clk
		.mem_if_ddr3_emif_0_pll_sharing_pll_locked                (<connected-to-mem_if_ddr3_emif_0_pll_sharing_pll_locked>),                //                                    .pll_locked
		.mem_if_ddr3_emif_0_pll_sharing_pll_write_clk_pre_phy_clk (<connected-to-mem_if_ddr3_emif_0_pll_sharing_pll_write_clk_pre_phy_clk>), //                                    .pll_write_clk_pre_phy_clk
		.mem_if_ddr3_emif_0_pll_sharing_pll_addr_cmd_clk          (<connected-to-mem_if_ddr3_emif_0_pll_sharing_pll_addr_cmd_clk>),          //                                    .pll_addr_cmd_clk
		.mem_if_ddr3_emif_0_pll_sharing_pll_avl_clk               (<connected-to-mem_if_ddr3_emif_0_pll_sharing_pll_avl_clk>),               //                                    .pll_avl_clk
		.mem_if_ddr3_emif_0_pll_sharing_pll_config_clk            (<connected-to-mem_if_ddr3_emif_0_pll_sharing_pll_config_clk>),            //                                    .pll_config_clk
		.mem_if_ddr3_emif_0_pll_sharing_pll_mem_phy_clk           (<connected-to-mem_if_ddr3_emif_0_pll_sharing_pll_mem_phy_clk>),           //                                    .pll_mem_phy_clk
		.mem_if_ddr3_emif_0_pll_sharing_afi_phy_clk               (<connected-to-mem_if_ddr3_emif_0_pll_sharing_afi_phy_clk>),               //                                    .afi_phy_clk
		.mem_if_ddr3_emif_0_pll_sharing_pll_avl_phy_clk           (<connected-to-mem_if_ddr3_emif_0_pll_sharing_pll_avl_phy_clk>),           //                                    .pll_avl_phy_clk
		.mem_if_ddr3_emif_0_status_local_init_done                (<connected-to-mem_if_ddr3_emif_0_status_local_init_done>),                //           mem_if_ddr3_emif_0_status.local_init_done
		.mem_if_ddr3_emif_0_status_local_cal_success              (<connected-to-mem_if_ddr3_emif_0_status_local_cal_success>),              //                                    .local_cal_success
		.mem_if_ddr3_emif_0_status_local_cal_fail                 (<connected-to-mem_if_ddr3_emif_0_status_local_cal_fail>),                 //                                    .local_cal_fail
		.mem_if_ddr3_emif_0_avl_waitrequest_n                     (<connected-to-mem_if_ddr3_emif_0_avl_waitrequest_n>),                     //              mem_if_ddr3_emif_0_avl.waitrequest_n
		.mem_if_ddr3_emif_0_avl_beginbursttransfer                (<connected-to-mem_if_ddr3_emif_0_avl_beginbursttransfer>),                //                                    .beginbursttransfer
		.mem_if_ddr3_emif_0_avl_address                           (<connected-to-mem_if_ddr3_emif_0_avl_address>),                           //                                    .address
		.mem_if_ddr3_emif_0_avl_readdatavalid                     (<connected-to-mem_if_ddr3_emif_0_avl_readdatavalid>),                     //                                    .readdatavalid
		.mem_if_ddr3_emif_0_avl_readdata                          (<connected-to-mem_if_ddr3_emif_0_avl_readdata>),                          //                                    .readdata
		.mem_if_ddr3_emif_0_avl_writedata                         (<connected-to-mem_if_ddr3_emif_0_avl_writedata>),                         //                                    .writedata
		.mem_if_ddr3_emif_0_avl_byteenable                        (<connected-to-mem_if_ddr3_emif_0_avl_byteenable>),                        //                                    .byteenable
		.mem_if_ddr3_emif_0_avl_read                              (<connected-to-mem_if_ddr3_emif_0_avl_read>),                              //                                    .read
		.mem_if_ddr3_emif_0_avl_write                             (<connected-to-mem_if_ddr3_emif_0_avl_write>),                             //                                    .write
		.mem_if_ddr3_emif_0_avl_burstcount                        (<connected-to-mem_if_ddr3_emif_0_avl_burstcount>),                        //                                    .burstcount
		.mem_if_ddr3_emif_0_afi_reset_export_reset_n              (<connected-to-mem_if_ddr3_emif_0_afi_reset_export_reset_n>),              // mem_if_ddr3_emif_0_afi_reset_export.reset_n
		.mem_if_ddr3_emif_0_afi_reset_reset_n                     (<connected-to-mem_if_ddr3_emif_0_afi_reset_reset_n>),                     //        mem_if_ddr3_emif_0_afi_reset.reset_n
		.mem_if_ddr3_emif_0_afi_half_clk_clk                      (<connected-to-mem_if_ddr3_emif_0_afi_half_clk_clk>),                      //     mem_if_ddr3_emif_0_afi_half_clk.clk
		.mem_if_ddr3_emif_0_afi_clk_clk                           (<connected-to-mem_if_ddr3_emif_0_afi_clk_clk>),                           //          mem_if_ddr3_emif_0_afi_clk.clk
		.clk_0_clk_reset_reset_n                                  (<connected-to-clk_0_clk_reset_reset_n>),                                  //                     clk_0_clk_reset.reset_n
		.clk_0_clk_clk                                            (<connected-to-clk_0_clk_clk>)                                             //                           clk_0_clk.clk
	);

